### ISSUE TITLE
[CLOSED] datatables-spring3 criteria resolver does not work with spring 3.1+ if using RequestMappingHandlerMethodAdapter

### ISSUE THREAD

**Issue by tduchateau** [dandelion/dandelion-datatables#176]
_Issue by **[gorder](https://github.com/gorder)** from Sunday Jul 21, 2013 at 03:20 GMT_

---

This would work...
see:
https://jira.springsource.org/browse/SPR-8234

/**
- A replacement for {@code DatatablesCriteriasResolver} which is not compatible with Spring 3.1+
- {@code RequestMappingHandlerMethodAdapter}
  */
  public class DatatablesCriteriasMethodArgumentResolver implements HandlerMethodArgumentResolver
  {
  
  @Override
  public boolean supportsParameter(MethodParameter parameter)
  {
      DatatablesParams parameterAnnotation = parameter
          .getParameterAnnotation(DatatablesParams.class);
      return null != parameterAnnotation;
  }
  
  @Override
  public Object resolveArgument(MethodParameter parameter, ModelAndViewContainer mavContainer,
      NativeWebRequest webRequest, WebDataBinderFactory binderFactory) throws Exception
  {
      HttpServletRequest request = (HttpServletRequest) webRequest.getNativeRequest();
      return DatatablesCriterias.getFromRequest(request);
  }

}

**Comment by mamadsolimani** [comment]
Hello sir, Filter Servlet changed package from "javax.servlet.Filter" to "jakarta.servlet.Filter" and "HttpServlet" to "jakarta.servlet.Servlet", dandelion doesn't work for me. I use JDK-21 and Spring boot 3.3.3 ... (dandelion version is 1.1.1)
