### ISSUE TITLE
Add support to export via AJAX when there are multiple tables

### ISSUE THREAD

**Issue by tduchateau** [dandelion/dandelion-datatables#223]
_Issue by **[dcervera](https://github.com/dcervera)** from Monday Nov 11, 2013 at 15:33 GMT_

---

Currently, [table export via AJAX](http://dandelion.github.io/datatables/tutorials/export/controller-based-exports.html) only works right when there is only one table in the page.
If there is more than one table, all the _export buttons_ export the same table, specifically, the last one.

That's because all the JS function that initiates the export process (function executed when you click on the _export button_) are named with the same name for all the tables in the page. That is, p.e. for PDF export function: 

```
ddl_dt_launch_export_pdf
```

To support export via AJAX for multiple tables it's necessary a way to name each _export function_ differently for each type (CSV​​, PDF, etc.) and for **each table**.

That's can be solved simply adding the ID of the table to the name of the _export function_ when its name is generated in [ExportManager.java](https://github.com/dandelion/dandelion-datatables/blob/master/datatables-core/src/main/java/com/github/dandelion/datatables/core/export/ExportManager.java), for both HTTP methods, that is:
- GET: [ExportManager.java - line 185](https://github.com/dandelion/dandelion-datatables/blob/master/datatables-core/src/main/java/com/github/dandelion/datatables/core/export/ExportManager.java#L185)
- POST: [ExportManager.java - line 185](https://github.com/dandelion/dandelion-datatables/blob/master/datatables-core/src/main/java/com/github/dandelion/datatables/core/export/ExportManager.java#L227)

**Comment by RavBhagdev** [comment]
I am not using AJAX method but thymeleaf and have the same problem.  Links to source above don't seem to work anymore. 

Any idea how I can configure or update this to get export to work for multiple tables?
