### ISSUE TITLE
Support for data tables 1.10

### ISSUE THREAD

**Issue by dev-tim** [dandelion/dandelion-datatables#241]
New datatables version was released, could you look at the possibility to integrate new version to the project?

**Comment by eruiz** [comment]
Hi Thibault, 

It's been a while since the last time we spoke :) We would like to include the new Datatables 1.10 and Dandelion Datatables 0.11 in gvNIX, do you have any estimated release date for new version 0.11?

Thanks

**Comment by tduchateau** [comment]
Hi pirate,

Certainly in Q2. 
Note that requirements have evolved, see https://github.com/dandelion/dandelion/blob/wip/0.11.0/dandelion-docs/src/asciidoc/_includes/requirements.adoc.

**Comment by eruiz** [comment]
Ok, thanks for pointing it ;)

**Comment by dev-tim** [comment]
Thanks
