### ISSUE TITLE
columnDef.isFilterable() always true

### ISSUE THREAD

**Issue by rafaelmembrives** [dandelion/dandelion-datatables#286]
I´m using dandelion-datatables with ThymeLeaf and `serverside="true"`. When I set `dt:filterable="true"` or `dt:filterable="false"`on the `<th>`´s the page render correctly the filter inputs but in server side  I always get `true` for all `columnDef.isFilterable()` in the `DatatablesCriterias`

Thanks you very much.

**Comment by tduchateau** [comment]
There's actually no issue here, but a badly chosen method name. `ColumnDef#isFilterable()` has nothing to do with `dt:filterable` but with `dt:searchable` instead. :-)

Thanks for reporting!
